### ISSUE TITLE
请教一下，怎样把 EasyAds 聚合sdk打成一个大的aar？

### ISSUE THREAD

**Issue by jhwsx** [bayescom/EasyAds-Android#8]

**Comment by jhwsx** [comment]
理解方式1的意思是这样的：先使用 fat-aar 提供的命令打出 easybd，easycsj，easyks，easyylh 这些广告模块的aar，然后再让 easyads 模块 embed 广告模块，这样就可以使用 fat-aar 提供的命令打出 easyads 的 aar，这里面就是所有的 aar 了。

**Comment by flayone** [comment]
你理解的这个没有问题～
但不是最简单的方式，最简单得方式是新建一个空的library，通过embed我们接入文档中SDK引入部分得各个依赖地址，然后将这个library打包成aar即可。
